# Set prefix
unbind C-b
unbind C-Space
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Pane management
bind-key x kill-pane # w/o confirmation
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R
bind-key - split-window -v -c "#{pane_current_path}"
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key S command-prompt -p "join-pane source:"  "join-pane -s :'%%'"
bind-key T command-prompt -p "join-pane target:"  "join-pane -t :'%%'"
bind-key A setw synchronize-panes\; display-message "synchronize-panes: #{?pane_synchronized,on,off}"

# Window management
bind-key & kill-window # w/o confirmation
bind-key -r "<" swap-window -d -t -1
bind-key -r ">" swap-window -d -t +1

# Window renaming
set -g allow-rename off
set -g renumber-windows on

# Show pane numbers until selected
bind -T prefix q display-panes -d 0

# Increase history limit
set -g history-limit 10000

# Vim-style copy
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection

# Allow mouse usage
set -g mouse on

# Colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_color "#888888"
set -g @catppuccin_window_middle_separator "█  "
set -g @catppuccin_window_right_separator "██ "
set -g @catppuccin_status_left_separator " █"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_status_modules_right "session host date_time"
set -g @catppuccin_date_time_text "%a %b %d %-I:%M %p"
set -g @catppuccin_status_background "default"

# Initialize TMUX plugin manager (keep at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
