# Set prefix
unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Use current path for new windows/panes
bind c new-window -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

# Managing panes
bind x kill-pane # w/o confirmation
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# Managing windows
bind & kill-window # w/o confirmation
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Disable window auto-renaming
set -g allow-rename off

# Renumber windows when they are deleted
set -g renumber-windows on

# Allow mouse usage
set -g mouse on

# Colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Vim style copy
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"

# Increase history limit
set -g history-limit 999999

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
