[colors.primary]
background = '#fafafa'
foreground = '#383a42'

[colors.normal]
black   = '#383a42'
red     = '#e45649'
green   = '#50a14f'
yellow  = '#c18401'
blue    = '#0184bc'
magenta = '#a626a4'
cyan    = '#0997b3'
white   = '#fafafa'

[colors.bright]
black   = '#a0a1a7'
red     = '#e45649'
green   = '#50a14f'
yellow  = '#c18401'
blue    = '#0184bc'
magenta = '#a626a4'
cyan    = '#0997b3'
white   = '#fafafa'

[colors.cursor]
text   = '#383a42'
cursor = '#bfceff'
