return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	dependencies = { "williamboman/mason.nvim" },
	opts = {
		run_on_start = true,
		auto_update = true,
		debounce_hours = 24,
		integrations = {
			["mason-lspconfig"] = false,
			["mason-null-ls"] = false,
			["mason-nvim-dap"] = false,
		},
		ensure_installed = {
			"bash-language-server",
			"debugpy",
			"delve",
			"dockerfile-language-server",
			"golangci-lint",
			"gopls",
			"json-lsp",
			"lua-language-server",
			"markdownlint",
			"mypy",
			"prettier",
			"pyright",
			"ruff",
			"shellcheck",
			"shfmt",
			"stylua",
			"taplo",
			"terraform-ls",
			"tflint",
			"vale",
			"yaml-language-server",
		},
	},
}
